[tasks.default]
alias = "all"

[tasks.format]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.lint]
toolchain = "nightly"
command = "cargo"
args = [
    "clippy", 
    ]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.all]
dependencies = [
    "format",
    "lint",
    "build",
    "test"
]
